// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package sqlc

import (
	"context"
	"database/sql"
)

const confidenceByGrade = `-- name: ConfidenceByGrade :many
SELECT
  predicted_grade,
  AVG(confidence) AS mean_confidence,
  MIN(confidence) AS min_confidence,
  COUNT(*) AS total
FROM ` + "`" + `scan` + "`" + `
WHERE status = 'done'
  AND predicted_grade IS NOT NULL
  AND (? = 1 OR created_by = ?)
  AND (? IS NULL OR created_at >= ?)
  AND (? IS NULL OR created_at <= ?)
GROUP BY predicted_grade
ORDER BY predicted_grade
`

type ConfidenceByGradeParams struct {
	AllScans  interface{}   `json:"all_scans"`
	CreatedBy sql.NullInt32 `json:"created_by"`
	FromTs    sql.NullInt32 `json:"from_ts"`
	ToTs      sql.NullInt32 `json:"to_ts"`
}

type ConfidenceByGradeRow struct {
	PredictedGrade sql.NullInt16 `json:"predicted_grade"`
	MeanConfidence interface{}   `json:"mean_confidence"`
	MinConfidence  interface{}   `json:"min_confidence"`
	Total          int64         `json:"total"`
}

func (q *Queries) ConfidenceByGrade(ctx context.Context, arg ConfidenceByGradeParams) ([]ConfidenceByGradeRow, error) {
	rows, err := q.db.QueryContext(ctx, confidenceByGrade,
		arg.AllScans,
		arg.CreatedBy,
		arg.FromTs,
		arg.FromTs,
		arg.ToTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConfidenceByGradeRow
	for rows.Next() {
		var i ConfidenceByGradeRow
		if err := rows.Scan(
			&i.PredictedGrade,
			&i.MeanConfidence,
			&i.MinConfidence,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const gradeDistribution = `-- name: GradeDistribution :many

SELECT predicted_grade, COUNT(*) AS total
FROM ` + "`" + `scan` + "`" + `
WHERE status = 'done'
  AND predicted_grade IS NOT NULL
  AND (? = 1 OR created_by = ?)
  AND (? IS NULL OR created_at >= ?)
  AND (? IS NULL OR created_at <= ?)
GROUP BY predicted_grade
ORDER BY predicted_grade
`

type GradeDistributionParams struct {
	AllScans  interface{}   `json:"all_scans"`
	CreatedBy sql.NullInt32 `json:"created_by"`
	FromTs    sql.NullInt32 `json:"from_ts"`
	ToTs      sql.NullInt32 `json:"to_ts"`
}

type GradeDistributionRow struct {
	PredictedGrade sql.NullInt16 `json:"predicted_grade"`
	Total          int64         `json:"total"`
}

// Analytics aggregate in SQL, never in Go: the scan table's indexes
// (idx_scan_grade_created, idx_scan_created_by) exist precisely so these stay
// cheap as the archive grows on a 2 GB box.
func (q *Queries) GradeDistribution(ctx context.Context, arg GradeDistributionParams) ([]GradeDistributionRow, error) {
	rows, err := q.db.QueryContext(ctx, gradeDistribution,
		arg.AllScans,
		arg.CreatedBy,
		arg.FromTs,
		arg.FromTs,
		arg.ToTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GradeDistributionRow
	for rows.Next() {
		var i GradeDistributionRow
		if err := rows.Scan(&i.PredictedGrade, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lowConfidenceScans = `-- name: LowConfidenceScans :many
SELECT id, patient_ref, notes, image_key, heatmap_key, image_sha256, predicted_grade, confidence, probabilities, model_id, model_sha256, inference_ms, status, error_message, created_at, created_by FROM ` + "`" + `scan` + "`" + `
WHERE status = 'done'
  AND confidence < ?
  AND (? = 1 OR created_by = ?)
  AND (? IS NULL OR created_at >= ?)
  AND (? IS NULL OR created_at <= ?)
ORDER BY confidence ASC, created_at DESC
LIMIT ?
`

type LowConfidenceScansParams struct {
	LowConfidence sql.NullFloat64 `json:"low_confidence"`
	AllScans      interface{}     `json:"all_scans"`
	CreatedBy     sql.NullInt32   `json:"created_by"`
	FromTs        sql.NullInt32   `json:"from_ts"`
	ToTs          sql.NullInt32   `json:"to_ts"`
	Limit         int32           `json:"limit"`
}

// At ~70% accuracy the model's own uncertainty is the most useful signal it
// produces; this queue is what makes the tool honest rather than oracular.
func (q *Queries) LowConfidenceScans(ctx context.Context, arg LowConfidenceScansParams) ([]Scan, error) {
	rows, err := q.db.QueryContext(ctx, lowConfidenceScans,
		arg.LowConfidence,
		arg.AllScans,
		arg.CreatedBy,
		arg.FromTs,
		arg.FromTs,
		arg.ToTs,
		arg.ToTs,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scan
	for rows.Next() {
		var i Scan
		if err := rows.Scan(
			&i.ID,
			&i.PatientRef,
			&i.Notes,
			&i.ImageKey,
			&i.HeatmapKey,
			&i.ImageSha256,
			&i.PredictedGrade,
			&i.Confidence,
			&i.Probabilities,
			&i.ModelID,
			&i.ModelSha256,
			&i.InferenceMs,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scansPerDay = `-- name: ScansPerDay :many
SELECT
  (created_at + ?) DIV 86400 AS day_index,
  COUNT(*) AS total,
  COALESCE(SUM(predicted_grade >= 2), 0) AS referable
FROM ` + "`" + `scan` + "`" + `
WHERE status = 'done'
  AND (? = 1 OR created_by = ?)
  AND (? IS NULL OR created_at >= ?)
  AND (? IS NULL OR created_at <= ?)
GROUP BY day_index
ORDER BY day_index
`

type ScansPerDayParams struct {
	TzOffset  sql.NullInt32 `json:"tz_offset"`
	AllScans  interface{}   `json:"all_scans"`
	CreatedBy sql.NullInt32 `json:"created_by"`
	FromTs    sql.NullInt32 `json:"from_ts"`
	ToTs      sql.NullInt32 `json:"to_ts"`
}

type ScansPerDayRow struct {
	DayIndex  int32       `json:"day_index"`
	Total     int64       `json:"total"`
	Referable interface{} `json:"referable"`
}

// Buckets by local calendar day without consulting the MySQL session time
// zone. FROM_UNIXTIME() would: it resolves @@session.time_zone, which defaults
// to SYSTEM (the DB host's OS zone) and which the DSN never pins, so its day
// keys could disagree with the days Go zero-fills the trend chart with -- and a
// key that disagrees drops that day's scans silently. Integer division of a
// shifted epoch has no such dependency: the caller passes its own UTC offset.
//
// The shift stays out of the WHERE clause on purpose, so created_at is still
// bare there and idx_scan_created_at remains usable.
func (q *Queries) ScansPerDay(ctx context.Context, arg ScansPerDayParams) ([]ScansPerDayRow, error) {
	rows, err := q.db.QueryContext(ctx, scansPerDay,
		arg.TzOffset,
		arg.AllScans,
		arg.CreatedBy,
		arg.FromTs,
		arg.FromTs,
		arg.ToTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScansPerDayRow
	for rows.Next() {
		var i ScansPerDayRow
		if err := rows.Scan(&i.DayIndex, &i.Total, &i.Referable); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryStats = `-- name: SummaryStats :one
SELECT
  COUNT(*) AS total_scans,
  COALESCE(SUM(predicted_grade >= 2), 0) AS referable_count,
  COALESCE(AVG(confidence), 0) AS mean_confidence,
  COALESCE(SUM(confidence < ?), 0) AS low_confidence_count,
  COALESCE(AVG(inference_ms), 0) AS mean_inference_ms
FROM ` + "`" + `scan` + "`" + `
WHERE status = 'done'
  AND (? = 1 OR created_by = ?)
  AND (? IS NULL OR created_at >= ?)
  AND (? IS NULL OR created_at <= ?)
`

type SummaryStatsParams struct {
	LowConfidence sql.NullFloat64 `json:"low_confidence"`
	AllScans      interface{}     `json:"all_scans"`
	CreatedBy     sql.NullInt32   `json:"created_by"`
	FromTs        sql.NullInt32   `json:"from_ts"`
	ToTs          sql.NullInt32   `json:"to_ts"`
}

type SummaryStatsRow struct {
	TotalScans         int64       `json:"total_scans"`
	ReferableCount     interface{} `json:"referable_count"`
	MeanConfidence     interface{} `json:"mean_confidence"`
	LowConfidenceCount interface{} `json:"low_confidence_count"`
	MeanInferenceMs    interface{} `json:"mean_inference_ms"`
}

// Referable DR (grade >= 2) is the clinically actionable threshold — the rate
// that decides whether a patient needs an ophthalmologist referral.
func (q *Queries) SummaryStats(ctx context.Context, arg SummaryStatsParams) (SummaryStatsRow, error) {
	row := q.db.QueryRowContext(ctx, summaryStats,
		arg.LowConfidence,
		arg.AllScans,
		arg.CreatedBy,
		arg.FromTs,
		arg.FromTs,
		arg.ToTs,
		arg.ToTs,
	)
	var i SummaryStatsRow
	err := row.Scan(
		&i.TotalScans,
		&i.ReferableCount,
		&i.MeanConfidence,
		&i.LowConfidenceCount,
		&i.MeanInferenceMs,
	)
	return i, err
}
