// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"encoding/json"
)

type AppSetting struct {
	SettingKey string `json:"setting_key"`
	// scalar; parsed by the typed accessor in store
	SettingValue string        `json:"setting_value"`
	UpdatedAt    sql.NullInt32 `json:"updated_at"`
	UpdatedBy    sql.NullInt32 `json:"updated_by"`
}

type Scan struct {
	ID int32 `json:"id"`
	// optional clinic-side patient identifier
	PatientRef sql.NullString `json:"patient_ref"`
	Notes      sql.NullString `json:"notes"`
	// storage key, not a URL — resolved via storage.URL()
	ImageKey string `json:"image_key"`
	// attention-rollout overlay
	HeatmapKey sql.NullString `json:"heatmap_key"`
	// dedupe + integrity
	ImageSha256 string `json:"image_sha256"`
	// 0..4 APTOS DR severity
	PredictedGrade sql.NullInt16 `json:"predicted_grade"`
	// top-1 softmax probability
	Confidence sql.NullFloat64 `json:"confidence"`
	// [p0,p1,p2,p3,p4]
	Probabilities json.RawMessage `json:"probabilities"`
	// provenance: predictions are model-specific
	ModelID     string        `json:"model_id"`
	ModelSha256 string        `json:"model_sha256"`
	InferenceMs sql.NullInt32 `json:"inference_ms"`
	// done | failed
	Status       string         `json:"status"`
	ErrorMessage sql.NullString `json:"error_message"`
	// OD | OS, read from the report label; NULL for a plain image upload
	Eye sql.NullString `json:"eye"`
	// image | pdf
	SourceKind string `json:"source_kind"`
	// groups the eyes of one report; not a storage key
	SourceRef sql.NullString `json:"source_ref"`
	// storage key of the retained source PDF, when STORAGE_KEEP_SOURCE_PDF
	SourceKey sql.NullString `json:"source_key"`
	CreatedAt sql.NullInt32  `json:"created_at"`
	CreatedBy sql.NullInt32  `json:"created_by"`
}

type User struct {
	ID    int32          `json:"id"`
	Name  sql.NullString `json:"name"`
	Email sql.NullString `json:"email"`
	// letter: required, number: optional, symbol: forbidden
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	// 1 = clinician, 2 = administrator
	Role int32 `json:"role"`
	// 1 = staff, 9 = superuser
	Subrole            int32         `json:"subrole"`
	MustChangePassword sql.NullInt32 `json:"must_change_password"`
	SuspendedAt        sql.NullInt32 `json:"suspended_at"`
	CreatedAt          sql.NullInt32 `json:"created_at"`
	UpdatedAt          sql.NullInt32 `json:"updated_at"`
	CreatedBy          sql.NullInt32 `json:"created_by"`
	UpdatedBy          sql.NullInt32 `json:"updated_by"`
}
