// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scan.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
)

const countScans = `-- name: CountScans :one
SELECT COUNT(*) FROM ` + "`" + `scan` + "`" + `
WHERE (? = 1 OR created_by = ?)
  AND (? IS NULL OR predicted_grade = ?)
  AND (? IS NULL OR patient_ref = ?)
  AND (? IS NULL OR created_at >= ?)
  AND (? IS NULL OR created_at <= ?)
`

type CountScansParams struct {
	AllScans   interface{}    `json:"all_scans"`
	CreatedBy  sql.NullInt32  `json:"created_by"`
	Grade      sql.NullInt16  `json:"grade"`
	PatientRef sql.NullString `json:"patient_ref"`
	FromTs     sql.NullInt32  `json:"from_ts"`
	ToTs       sql.NullInt32  `json:"to_ts"`
}

func (q *Queries) CountScans(ctx context.Context, arg CountScansParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countScans,
		arg.AllScans,
		arg.CreatedBy,
		arg.Grade,
		arg.Grade,
		arg.PatientRef,
		arg.PatientRef,
		arg.FromTs,
		arg.FromTs,
		arg.ToTs,
		arg.ToTs,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScan = `-- name: CreateScan :execresult
INSERT INTO ` + "`" + `scan` + "`" + ` (
  patient_ref, notes, image_key, heatmap_key, image_sha256,
  predicted_grade, confidence, probabilities,
  model_id, model_sha256, inference_ms,
  status, error_message, eye, source_kind, source_ref, source_key, created_at, created_by
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateScanParams struct {
	PatientRef     sql.NullString  `json:"patient_ref"`
	Notes          sql.NullString  `json:"notes"`
	ImageKey       string          `json:"image_key"`
	HeatmapKey     sql.NullString  `json:"heatmap_key"`
	ImageSha256    string          `json:"image_sha256"`
	PredictedGrade sql.NullInt16   `json:"predicted_grade"`
	Confidence     sql.NullFloat64 `json:"confidence"`
	Probabilities  json.RawMessage `json:"probabilities"`
	ModelID        string          `json:"model_id"`
	ModelSha256    string          `json:"model_sha256"`
	InferenceMs    sql.NullInt32   `json:"inference_ms"`
	Status         string          `json:"status"`
	ErrorMessage   sql.NullString  `json:"error_message"`
	Eye            sql.NullString  `json:"eye"`
	SourceKind     string          `json:"source_kind"`
	SourceRef      sql.NullString  `json:"source_ref"`
	SourceKey      sql.NullString  `json:"source_key"`
	CreatedAt      sql.NullInt32   `json:"created_at"`
	CreatedBy      sql.NullInt32   `json:"created_by"`
}

func (q *Queries) CreateScan(ctx context.Context, arg CreateScanParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createScan,
		arg.PatientRef,
		arg.Notes,
		arg.ImageKey,
		arg.HeatmapKey,
		arg.ImageSha256,
		arg.PredictedGrade,
		arg.Confidence,
		arg.Probabilities,
		arg.ModelID,
		arg.ModelSha256,
		arg.InferenceMs,
		arg.Status,
		arg.ErrorMessage,
		arg.Eye,
		arg.SourceKind,
		arg.SourceRef,
		arg.SourceKey,
		arg.CreatedAt,
		arg.CreatedBy,
	)
}

const deleteScan = `-- name: DeleteScan :exec
DELETE FROM ` + "`" + `scan` + "`" + `
WHERE id = ?
  AND (? = 1 OR created_by = ?)
`

type DeleteScanParams struct {
	ID        int32         `json:"id"`
	AllScans  interface{}   `json:"all_scans"`
	CreatedBy sql.NullInt32 `json:"created_by"`
}

func (q *Queries) DeleteScan(ctx context.Context, arg DeleteScanParams) error {
	_, err := q.db.ExecContext(ctx, deleteScan, arg.ID, arg.AllScans, arg.CreatedBy)
	return err
}

const getScan = `-- name: GetScan :one
SELECT id, patient_ref, notes, image_key, heatmap_key, image_sha256, predicted_grade, confidence, probabilities, model_id, model_sha256, inference_ms, status, error_message, eye, source_kind, source_ref, source_key, created_at, created_by FROM ` + "`" + `scan` + "`" + ` WHERE id = ? LIMIT 1
`

func (q *Queries) GetScan(ctx context.Context, id int32) (Scan, error) {
	row := q.db.QueryRowContext(ctx, getScan, id)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.PatientRef,
		&i.Notes,
		&i.ImageKey,
		&i.HeatmapKey,
		&i.ImageSha256,
		&i.PredictedGrade,
		&i.Confidence,
		&i.Probabilities,
		&i.ModelID,
		&i.ModelSha256,
		&i.InferenceMs,
		&i.Status,
		&i.ErrorMessage,
		&i.Eye,
		&i.SourceKind,
		&i.SourceRef,
		&i.SourceKey,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getScanForUser = `-- name: GetScanForUser :one
SELECT id, patient_ref, notes, image_key, heatmap_key, image_sha256, predicted_grade, confidence, probabilities, model_id, model_sha256, inference_ms, status, error_message, eye, source_kind, source_ref, source_key, created_at, created_by FROM ` + "`" + `scan` + "`" + `
WHERE id = ?
  AND (? = 1 OR created_by = ?)
LIMIT 1
`

type GetScanForUserParams struct {
	ID        int32         `json:"id"`
	AllScans  interface{}   `json:"all_scans"`
	CreatedBy sql.NullInt32 `json:"created_by"`
}

// Role scoping lives in the query, not in Go: a clinician may only read their
// own scans, and passing sqlc.arg(all_scans) = 1 for admins keeps the two
// paths on a single statement so they cannot drift apart.
func (q *Queries) GetScanForUser(ctx context.Context, arg GetScanForUserParams) (Scan, error) {
	row := q.db.QueryRowContext(ctx, getScanForUser, arg.ID, arg.AllScans, arg.CreatedBy)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.PatientRef,
		&i.Notes,
		&i.ImageKey,
		&i.HeatmapKey,
		&i.ImageSha256,
		&i.PredictedGrade,
		&i.Confidence,
		&i.Probabilities,
		&i.ModelID,
		&i.ModelSha256,
		&i.InferenceMs,
		&i.Status,
		&i.ErrorMessage,
		&i.Eye,
		&i.SourceKind,
		&i.SourceRef,
		&i.SourceKey,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listScans = `-- name: ListScans :many
SELECT id, patient_ref, notes, image_key, heatmap_key, image_sha256, predicted_grade, confidence, probabilities, model_id, model_sha256, inference_ms, status, error_message, eye, source_kind, source_ref, source_key, created_at, created_by FROM ` + "`" + `scan` + "`" + `
WHERE (? = 1 OR created_by = ?)
  AND (? IS NULL OR predicted_grade = ?)
  AND (? IS NULL OR patient_ref = ?)
  AND (? IS NULL OR created_at >= ?)
  AND (? IS NULL OR created_at <= ?)
ORDER BY created_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListScansParams struct {
	AllScans   interface{}    `json:"all_scans"`
	CreatedBy  sql.NullInt32  `json:"created_by"`
	Grade      sql.NullInt16  `json:"grade"`
	PatientRef sql.NullString `json:"patient_ref"`
	FromTs     sql.NullInt32  `json:"from_ts"`
	ToTs       sql.NullInt32  `json:"to_ts"`
	Limit      int32          `json:"limit"`
	Offset     int32          `json:"offset"`
}

func (q *Queries) ListScans(ctx context.Context, arg ListScansParams) ([]Scan, error) {
	rows, err := q.db.QueryContext(ctx, listScans,
		arg.AllScans,
		arg.CreatedBy,
		arg.Grade,
		arg.Grade,
		arg.PatientRef,
		arg.PatientRef,
		arg.FromTs,
		arg.FromTs,
		arg.ToTs,
		arg.ToTs,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scan
	for rows.Next() {
		var i Scan
		if err := rows.Scan(
			&i.ID,
			&i.PatientRef,
			&i.Notes,
			&i.ImageKey,
			&i.HeatmapKey,
			&i.ImageSha256,
			&i.PredictedGrade,
			&i.Confidence,
			&i.Probabilities,
			&i.ModelID,
			&i.ModelSha256,
			&i.InferenceMs,
			&i.Status,
			&i.ErrorMessage,
			&i.Eye,
			&i.SourceKind,
			&i.SourceRef,
			&i.SourceKey,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScansBySourceRef = `-- name: ListScansBySourceRef :many
SELECT id, patient_ref, notes, image_key, heatmap_key, image_sha256, predicted_grade, confidence, probabilities, model_id, model_sha256, inference_ms, status, error_message, eye, source_kind, source_ref, source_key, created_at, created_by FROM ` + "`" + `scan` + "`" + `
WHERE source_ref = ?
  AND (? = 1 OR created_by = ?)
ORDER BY eye, id
`

type ListScansBySourceRefParams struct {
	SourceRef sql.NullString `json:"source_ref"`
	AllScans  interface{}    `json:"all_scans"`
	CreatedBy sql.NullInt32  `json:"created_by"`
}

// Both eyes of one PDF report share a source_ref, which is what lets the detail
// page offer the other eye without a separate exam table. It is a plain grouping
// token, so it works whether or not the report itself was retained.
func (q *Queries) ListScansBySourceRef(ctx context.Context, arg ListScansBySourceRefParams) ([]Scan, error) {
	rows, err := q.db.QueryContext(ctx, listScansBySourceRef, arg.SourceRef, arg.AllScans, arg.CreatedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scan
	for rows.Next() {
		var i Scan
		if err := rows.Scan(
			&i.ID,
			&i.PatientRef,
			&i.Notes,
			&i.ImageKey,
			&i.HeatmapKey,
			&i.ImageSha256,
			&i.PredictedGrade,
			&i.Confidence,
			&i.Probabilities,
			&i.ModelID,
			&i.ModelSha256,
			&i.InferenceMs,
			&i.Status,
			&i.ErrorMessage,
			&i.Eye,
			&i.SourceKind,
			&i.SourceRef,
			&i.SourceKey,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentScans = `-- name: RecentScans :many
SELECT id, patient_ref, notes, image_key, heatmap_key, image_sha256, predicted_grade, confidence, probabilities, model_id, model_sha256, inference_ms, status, error_message, eye, source_kind, source_ref, source_key, created_at, created_by FROM ` + "`" + `scan` + "`" + `
WHERE (? = 1 OR created_by = ?)
  AND status = 'done'
ORDER BY created_at DESC, id DESC
LIMIT ?
`

type RecentScansParams struct {
	AllScans  interface{}   `json:"all_scans"`
	CreatedBy sql.NullInt32 `json:"created_by"`
	Limit     int32         `json:"limit"`
}

func (q *Queries) RecentScans(ctx context.Context, arg RecentScansParams) ([]Scan, error) {
	rows, err := q.db.QueryContext(ctx, recentScans, arg.AllScans, arg.CreatedBy, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scan
	for rows.Next() {
		var i Scan
		if err := rows.Scan(
			&i.ID,
			&i.PatientRef,
			&i.Notes,
			&i.ImageKey,
			&i.HeatmapKey,
			&i.ImageSha256,
			&i.PredictedGrade,
			&i.Confidence,
			&i.Probabilities,
			&i.ModelID,
			&i.ModelSha256,
			&i.InferenceMs,
			&i.Status,
			&i.ErrorMessage,
			&i.Eye,
			&i.SourceKind,
			&i.SourceRef,
			&i.SourceKey,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
