// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: setting.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getSetting = `-- name: GetSetting :one

SELECT setting_key, setting_value, updated_at, updated_by FROM ` + "`" + `app_setting` + "`" + ` WHERE setting_key = ? LIMIT 1
`

// Runtime-mutable application settings.
//
// Values are scalars stored as text and parsed by the typed accessors in
// package store. An absent row means "no preference expressed", which the
// caller resolves to its own default — it is not the same as a stored false.
func (q *Queries) GetSetting(ctx context.Context, settingKey string) (AppSetting, error) {
	row := q.db.QueryRowContext(ctx, getSetting, settingKey)
	var i AppSetting
	err := row.Scan(
		&i.SettingKey,
		&i.SettingValue,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listSettings = `-- name: ListSettings :many
SELECT setting_key, setting_value, updated_at, updated_by FROM ` + "`" + `app_setting` + "`" + ` ORDER BY setting_key
`

func (q *Queries) ListSettings(ctx context.Context) ([]AppSetting, error) {
	rows, err := q.db.QueryContext(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppSetting
	for rows.Next() {
		var i AppSetting
		if err := rows.Scan(
			&i.SettingKey,
			&i.SettingValue,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO ` + "`" + `app_setting` + "`" + ` (setting_key, setting_value, updated_at, updated_by)
VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  setting_value = VALUES(setting_value),
  updated_at = VALUES(updated_at),
  updated_by = VALUES(updated_by)
`

type UpsertSettingParams struct {
	SettingKey   string        `json:"setting_key"`
	SettingValue string        `json:"setting_value"`
	UpdatedAt    sql.NullInt32 `json:"updated_at"`
	UpdatedBy    sql.NullInt32 `json:"updated_by"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting,
		arg.SettingKey,
		arg.SettingValue,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	return err
}
