// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"
	"database/sql"
)

const adminSetUserPassword = `-- name: AdminSetUserPassword :exec
UPDATE ` + "`" + `user` + "`" + `
SET password_hash = ?, must_change_password = 1, updated_at = ?, updated_by = ?
WHERE id = ?
`

type AdminSetUserPasswordParams struct {
	PasswordHash string        `json:"password_hash"`
	UpdatedAt    sql.NullInt32 `json:"updated_at"`
	UpdatedBy    sql.NullInt32 `json:"updated_by"`
	ID           int32         `json:"id"`
}

// AdminSetUserPassword flags the account like CreateUser does: the password was
// chosen by an administrator, not by the account holder.
func (q *Queries) AdminSetUserPassword(ctx context.Context, arg AdminSetUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, adminSetUserPassword,
		arg.PasswordHash,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM ` + "`" + `user` + "`" + `
WHERE (? IS NULL OR role = ?)
`

type CountUsersParams struct {
	Role sql.NullInt32 `json:"role"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers, arg.Role, arg.Role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByRole = `-- name: CountUsersByRole :one
SELECT COUNT(*) FROM ` + "`" + `user` + "`" + ` WHERE role = ?
`

func (q *Queries) CountUsersByRole(ctx context.Context, role int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByRole, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO ` + "`" + `user` + "`" + ` (
  name, email, username, password_hash, role, subrole,
  must_change_password, created_at, updated_at, created_by, updated_by
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	Name               sql.NullString `json:"name"`
	Email              string         `json:"email"`
	Username           string         `json:"username"`
	PasswordHash       string         `json:"password_hash"`
	Role               int32          `json:"role"`
	Subrole            int32          `json:"subrole"`
	MustChangePassword sql.NullInt32  `json:"must_change_password"`
	CreatedAt          sql.NullInt32  `json:"created_at"`
	UpdatedAt          sql.NullInt32  `json:"updated_at"`
	CreatedBy          sql.NullInt32  `json:"created_by"`
	UpdatedBy          sql.NullInt32  `json:"updated_by"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.Subrole,
		arg.MustChangePassword,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM ` + "`" + `user` + "`" + `
WHERE ` + "`" + `user` + "`" + `.id = ?
  AND NOT EXISTS (SELECT 1 FROM ` + "`" + `scan` + "`" + ` s WHERE s.created_by = ` + "`" + `user` + "`" + `.id)
`

// DeleteUser refuses an account that owns scans. fk_scan_created_by would
// otherwise null out their created_by, silently orphaning clinical records.
func (q *Queries) DeleteUser(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, username, password_hash, role, subrole, must_change_password, suspended_at, created_at, updated_at, created_by, updated_by FROM ` + "`" + `user` + "`" + ` WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Subrole,
		&i.MustChangePassword,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, username, password_hash, role, subrole, must_change_password, suspended_at, created_at, updated_at, created_by, updated_by FROM ` + "`" + `user` + "`" + ` WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Subrole,
		&i.MustChangePassword,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, name, email, username, password_hash, role, subrole, must_change_password, suspended_at, created_at, updated_at, created_by, updated_by FROM ` + "`" + `user` + "`" + ` WHERE username = ? LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Subrole,
		&i.MustChangePassword,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u.name, u.email, u.username, u.password_hash, u.role, u.subrole, u.must_change_password, u.suspended_at, u.created_at, u.updated_at, u.created_by, u.updated_by, (SELECT COUNT(*) FROM ` + "`" + `scan` + "`" + ` s WHERE s.created_by = u.id) AS scan_count
FROM ` + "`" + `user` + "`" + ` u
WHERE (? IS NULL OR u.role = ?)
ORDER BY u.id DESC
LIMIT ? OFFSET ?
`

type ListUsersParams struct {
	Role   sql.NullInt32 `json:"role"`
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
}

type ListUsersRow struct {
	ID                 int32          `json:"id"`
	Name               sql.NullString `json:"name"`
	Email              string         `json:"email"`
	Username           string         `json:"username"`
	PasswordHash       string         `json:"password_hash"`
	Role               int32          `json:"role"`
	Subrole            int32          `json:"subrole"`
	MustChangePassword sql.NullInt32  `json:"must_change_password"`
	SuspendedAt        sql.NullInt32  `json:"suspended_at"`
	CreatedAt          sql.NullInt32  `json:"created_at"`
	UpdatedAt          sql.NullInt32  `json:"updated_at"`
	CreatedBy          sql.NullInt32  `json:"created_by"`
	UpdatedBy          sql.NullInt32  `json:"updated_by"`
	ScanCount          int64          `json:"scan_count"`
}

// scan_count decides whether the account may be deleted; idx_scan_created_by
// keeps the subquery to an index range per listed row.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers,
		arg.Role,
		arg.Role,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Username,
			&i.PasswordHash,
			&i.Role,
			&i.Subrole,
			&i.MustChangePassword,
			&i.SuspendedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.ScanCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetUserPassword = `-- name: ResetUserPassword :execrows
UPDATE ` + "`" + `user` + "`" + `
SET password_hash = ?, must_change_password = NULL,
    updated_at = ?, updated_by = ?
WHERE id = ? AND password_hash = ?
`

type ResetUserPasswordParams struct {
	NewHash   string        `json:"new_hash"`
	UpdatedAt sql.NullInt32 `json:"updated_at"`
	UpdatedBy sql.NullInt32 `json:"updated_by"`
	ID        int32         `json:"id"`
	OldHash   string        `json:"old_hash"`
}

// ResetUserPassword only matches while the hash is still the one the reset link
// was issued against, so two submissions of the same link cannot both succeed.
func (q *Queries) ResetUserPassword(ctx context.Context, arg ResetUserPasswordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resetUserPassword,
		arg.NewHash,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
		arg.OldHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setUserSuspended = `-- name: SetUserSuspended :exec
UPDATE ` + "`" + `user` + "`" + ` SET suspended_at = ?, updated_at = ?, updated_by = ? WHERE id = ?
`

type SetUserSuspendedParams struct {
	SuspendedAt sql.NullInt32 `json:"suspended_at"`
	UpdatedAt   sql.NullInt32 `json:"updated_at"`
	UpdatedBy   sql.NullInt32 `json:"updated_by"`
	ID          int32         `json:"id"`
}

func (q *Queries) SetUserSuspended(ctx context.Context, arg SetUserSuspendedParams) error {
	_, err := q.db.ExecContext(ctx, setUserSuspended,
		arg.SuspendedAt,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE ` + "`" + `user` + "`" + `
SET name = ?, email = ?, username = ?, role = ?, updated_at = ?, updated_by = ?
WHERE id = ?
`

type UpdateUserParams struct {
	Name      sql.NullString `json:"name"`
	Email     string         `json:"email"`
	Username  string         `json:"username"`
	Role      int32          `json:"role"`
	UpdatedAt sql.NullInt32  `json:"updated_at"`
	UpdatedBy sql.NullInt32  `json:"updated_by"`
	ID        int32          `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.Username,
		arg.Role,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE ` + "`" + `user` + "`" + `
SET password_hash = ?, must_change_password = NULL, updated_at = ?, updated_by = ?
WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string        `json:"password_hash"`
	UpdatedAt    sql.NullInt32 `json:"updated_at"`
	UpdatedBy    sql.NullInt32 `json:"updated_by"`
	ID           int32         `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword,
		arg.PasswordHash,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}
