// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM ` + "`" + `user` + "`" + `
WHERE (? IS NULL OR role = ?)
`

type CountUsersParams struct {
	Role sql.NullInt32 `json:"role"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers, arg.Role, arg.Role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByRole = `-- name: CountUsersByRole :one
SELECT COUNT(*) FROM ` + "`" + `user` + "`" + ` WHERE role = ?
`

func (q *Queries) CountUsersByRole(ctx context.Context, role int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByRole, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO ` + "`" + `user` + "`" + ` (
  name, email, username, password_hash, role, subrole,
  must_change_password, created_at, updated_at, created_by, updated_by
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	Name               sql.NullString `json:"name"`
	Email              sql.NullString `json:"email"`
	Username           string         `json:"username"`
	PasswordHash       string         `json:"password_hash"`
	Role               int32          `json:"role"`
	Subrole            int32          `json:"subrole"`
	MustChangePassword sql.NullInt32  `json:"must_change_password"`
	CreatedAt          sql.NullInt32  `json:"created_at"`
	UpdatedAt          sql.NullInt32  `json:"updated_at"`
	CreatedBy          sql.NullInt32  `json:"created_by"`
	UpdatedBy          sql.NullInt32  `json:"updated_by"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.Subrole,
		arg.MustChangePassword,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM ` + "`" + `user` + "`" + ` WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, username, password_hash, role, subrole, must_change_password, suspended_at, created_at, updated_at, created_by, updated_by FROM ` + "`" + `user` + "`" + ` WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Subrole,
		&i.MustChangePassword,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, name, email, username, password_hash, role, subrole, must_change_password, suspended_at, created_at, updated_at, created_by, updated_by FROM ` + "`" + `user` + "`" + ` WHERE username = ? LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Subrole,
		&i.MustChangePassword,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, username, password_hash, role, subrole, must_change_password, suspended_at, created_at, updated_at, created_by, updated_by FROM ` + "`" + `user` + "`" + `
WHERE (? IS NULL OR role = ?)
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListUsersParams struct {
	Role   sql.NullInt32 `json:"role"`
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers,
		arg.Role,
		arg.Role,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Username,
			&i.PasswordHash,
			&i.Role,
			&i.Subrole,
			&i.MustChangePassword,
			&i.SuspendedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserSuspended = `-- name: SetUserSuspended :exec
UPDATE ` + "`" + `user` + "`" + ` SET suspended_at = ?, updated_at = ?, updated_by = ? WHERE id = ?
`

type SetUserSuspendedParams struct {
	SuspendedAt sql.NullInt32 `json:"suspended_at"`
	UpdatedAt   sql.NullInt32 `json:"updated_at"`
	UpdatedBy   sql.NullInt32 `json:"updated_by"`
	ID          int32         `json:"id"`
}

func (q *Queries) SetUserSuspended(ctx context.Context, arg SetUserSuspendedParams) error {
	_, err := q.db.ExecContext(ctx, setUserSuspended,
		arg.SuspendedAt,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE ` + "`" + `user` + "`" + `
SET name = ?, email = ?, role = ?, subrole = ?, updated_at = ?, updated_by = ?
WHERE id = ?
`

type UpdateUserParams struct {
	Name      sql.NullString `json:"name"`
	Email     sql.NullString `json:"email"`
	Role      int32          `json:"role"`
	Subrole   int32          `json:"subrole"`
	UpdatedAt sql.NullInt32  `json:"updated_at"`
	UpdatedBy sql.NullInt32  `json:"updated_by"`
	ID        int32          `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.Role,
		arg.Subrole,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE ` + "`" + `user` + "`" + `
SET password_hash = ?, must_change_password = NULL, updated_at = ?, updated_by = ?
WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string        `json:"password_hash"`
	UpdatedAt    sql.NullInt32 `json:"updated_at"`
	UpdatedBy    sql.NullInt32 `json:"updated_by"`
	ID           int32         `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword,
		arg.PasswordHash,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}
